### ISSUE TITLE
Update At-Sea Safety Manual

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/EBS-Survey-Planning#45]

**Comment by NicoleCharriere-NOAA** [comment]
```[tasklist]
### Tasks
- [ ] Update safety manual through FAST
- [ ] Send to supervisors for approval
- [ ] Upload to Google Drive Survey App form
```
